import React from "react";
import Head from "next/head";
import { GetServerSideProps, GetStaticProps } from "next";
import { Tab } from "@headlessui/react";

import { Header, Banner, Products, Footer, Cart } from "../components";
import { fetchCategories } from "../Util/fetchCategories";
import { fetchProducts } from "../Util/fetchProducts";

interface Props {
  categories: Category[];
  products: Product[];
}

const index = ({ categories, products }: Props) => {
  const showProducts = (category: number) => {
    return products
      .filter((product) => product.category._ref === categories[category]._id)
      .map((product) => <Products product={product} key={product._id} />); // filter products by category
  };

  return (
    <div className="relative">
      <Head>
        <title>Moblie E-Shop</title>
        <meta name="description" content="Generated by Alireza Barkhordari" />
      </Head>
      {/* The Header & Banner Section */}
      <div className="h-screen">
        <Header />
        <Banner />
      </div>
      <Cart />
      {/* Show Products Section */}
      <div className="min-h-screen mb-32">
        <Tab.Group>
          <Tab.List className="flex justify-center mt-10">
            {categories.map((category) => (
              <Tab
                key={category._id}
                id={category._id}
                className={({ selected }) =>
                  `whitespace-nowrap rounded-t-md w-[150px] py-2 px-6 text-sm font-semibold outline-none md:py-3 md:px-8 md:text-lg transition-all duration-200 ${
                    selected
                      ? "borderGradient text-white bg-mainblue text-[#fff]"
                      : "border-b-2 border-mainblue text-mainblue"
                  }`
                }>
                {category.title}
              </Tab>
            ))}
          </Tab.List>
          <Tab.Panels className="mx-auto mt-8 max-w-fit pt-10 pb-24 sm:px-4">
            <Tab.Panel className="tabPanel">{showProducts(0)}</Tab.Panel>
            <Tab.Panel className="tabPanel">{showProducts(1)}</Tab.Panel>
            <Tab.Panel className="tabPanel">{showProducts(2)}</Tab.Panel>
          </Tab.Panels>
        </Tab.Group>
      </div>
      <Footer />
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const categories = await fetchCategories();
  const products = await fetchProducts();
  return {
    props: { categories, products }, // will be passed to the page component as props
  };
};

export default index;
